### PR TITLE
support additional claims

### LINKED ISSUE #2: Custom claims?
Hi!  Thanks for helping making openid connect a lot less complicated with this crate!

Is there any support for <del>custom</del> <ins>additional</ins> claims?  Or plans for such support?  I didn't find anything in the docs.

### PR DESCRIPTION
**Pull request by kilork**
fixes #2

### CODE REVIEW

**Comment by kaj** [comment]
Yes, I have gotten my additional claims to work with this code!

I had to have quite a lot of local code though.  As my local `Claims` type have to impl `openid::Claims` which requires accessors for a lot of fields, I ended up doing:

```rust
#[derive(Debug, Deserialize, Serialize)]
pub struct KthClaims {
    #[serde(flatten)]
    base: openid::StandardClaims,

    #[serde(rename = "http://schema.my.org/internal/field_a")]
    my_a: String,

    #[serde(rename = "http://schema.my.org/internal/field_b", deserialize_with="from_base64")]
    my_b: String,
}

impl openid::Claims for KthClaims {
    fn iss(&self) -> &url::Url { self.base.iss() }
    fn sub(&self) -> &str { self.base.sub() }
    fn aud(&self) -> &biscuit::SingleOrMultiple<String> { self.base.aud() }
    fn exp(&self) -> i64 { self.base.exp() }
    fn iat(&self) -> i64 { self.base.iat() }
    fn auth_time(&self) -> Option<i64> { self.base.auth_time() }
    fn nonce(&self) -> Option<&std::string::String> { self.base.nonce() }
    fn at_hash(&self) -> Option<&String> { self.base.at_hash() }
    fn c_hash(&self) -> Option<&String> { self.base.c_hash() }
    fn acr(&self) -> Option<&String> { self.base.acr() }
    fn amr(&self) -> Option<&Vec<String>> { self.base.amr() }
    fn azp(&self) -> Option<&String> { self.base.azp() }
    fn userinfo(&self) -> &openid::Userinfo { self.base.userinfo() }
}

impl openid::CompactJson for KthClaims { }
```
I think turning this around to what I call alternative (3) in #2 would make it a lot more convenient to use.  Maybe I should try to create a separate PR for that, and then we can compare both variants before selecting which one to merge?

**Comment by kaj** [comment]
Also, If we choose this path, I think `openid` should reexport either the `SingleOrMultiple` type or the entire `biscuit` module, to not force code using it to have a separate dependency of `biscuit`.

**Comment by kilork** [comment]
@kaj Thanks for the feedback, just implemented a kind of auto trait, so you do not need to have that much code. See `CustomClaims`. 

Example:
```rust
use openid::{Claims, CompactJson, CustomClaims, StandardClaims, Client, Discovered};
use openid::provider::google::Installed;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize)]
struct MyClaims {
    my_claim: Option<String>,
    #[serde(flatten)]
    standard_claims: StandardClaims,
}

impl CustomClaims for MyClaims {
    fn standard_claims(&self) -> &StandardClaims {
        &self.standard_claims
    }
}

impl CompactJson for MyClaims {}

let client: Client<Installed, MyClaims> = Client::new(
    Installed,
    String::from("CLIENT_ID"),
    String::from("CLIENT_SECRET"),
    Some(String::from("urn:ietf:wg:oauth:2.0:oob")),
    reqwest::Client::new(), None,
);
```

I would also think about adding `ExtendedClaims` as `StandardClaims` + <User defined struct>. But I think it is already not that bad. What do you think?

**Comment by kilork** [comment]
Nope, `ExtendedClaims` does not seem to be that easy :)

**Comment by kaj** [comment]
That seems quite nice!  I'll try it out tomorrow (it's just part midnight in mhy timezone as I write this).

And my conclusion for "alternative 3" is pretty much the same as yours for `ExtendedClaims`: Getting those types right i a lot harder than I would have imagined.

**Comment by kaj** [comment]
Yes, this works great!

**Comment by kilork** [comment]
Cool, going to merge it as new release. Thanks!

**Pull request merged**
